// This file is automatically generated. Do not edit it directly.

// Your Opix credentials
export const CLIENT_ID = "<data.id from step 3>";
export const API_KEY = "opx_your_key_here";

// Import your Opix SDK factory
import { createClient } from "./sdk";

// Import the Opix client like this:
// import { opix } from "@/integrations/opix/client";

export const opix = createClient(CLIENT_ID, API_KEY);
