// This file is automatically generated. Do not edit it directly.

// Your Opix credentials
export const CLIENT_ID = import.meta.env.VITE_OPIX_API_KEY;
export const API_KEY = import.meta.env.VITE_OPIX_CLIENT_ID;

// Import your Opix SDK factory
import { createClient } from "./sdk";

// Import the Opix client like this:
// import { opix } from "@/integrations/opix/client";

export const opix = createClient(CLIENT_ID, API_KEY);
